tax = {'taxes': [{'account_analytic_collected_id': False,
                  'account_analytic_paid_id': False,
                  'account_collected_id': False,
                  'account_paid_id': False,
                  'amount': 7.8100000000000005,
                  'base_code_id': False,
                  'base_sign': 1.0,
                  'id': 43,
                  'name': u'ISC 10% Almuerzo Incluido',
                  'price_unit': 78.125,
                  'ref_base_code_id': False,
                  'ref_base_sign': 1.0,
                  'ref_tax_code_id': False,
                  'ref_tax_sign': 1.0,
                  'sequence': 1,
                  'tax_code_id': False,
                  'tax_sign': 1.0,
                  'todo': 0},
                 {'account_analytic_collected_id': False,
                  'account_analytic_paid_id': False,
                  'account_collected_id': 6036,
                  'account_paid_id': 6036,
                  'amount': 14.06,
                  'base_code_id': False,
                  'base_sign': 1.0,
                  'id': 15,
                  'name': u'ITBIS 18% Servicios Incluido',
                  'price_unit': 78.125,
                  'ref_base_code_id': False,
                  'ref_base_sign': 1.0,
                  'ref_tax_code_id': 29,
                  'ref_tax_sign': 1.0,
                  'sequence': 1,
                  'tax_code_id': 29,
                  'tax_sign': -1.0,
                  'todo': 0}],
       'total': 78.13,
       'total_included': 100.0}
